wandb_version: 1

seed:
  desc: null
  value: 1
episodes:
  desc: null
  value: 20000
evaluation_episodes:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 128
gamma:
  desc: null
  value: 0.9
inverting_gradients:
  desc: null
  value: true
initial_memory_threshold:
  desc: null
  value: 500
replay_memory_size:
  desc: null
  value: 10000
epsilon_steps:
  desc: null
  value: 1000
tau_actor:
  desc: null
  value: 0.1
tau_actor_param:
  desc: null
  value: 0.001
use_ornstein_noise:
  desc: null
  value: true
learning_rate_actor:
  desc: null
  value: 0.001
learning_rate_actor_param:
  desc: null
  value: 0.0001
epsilon_final:
  desc: null
  value: 0.01
zero_index_gradients:
  desc: null
  value: false
initialise_params:
  desc: null
  value: true
scale_actions:
  desc: null
  value: true
clip_grad:
  desc: null
  value: 10.0
split:
  desc: null
  value: false
indexed:
  desc: null
  value: false
layers:
  desc: null
  value:
  - 128
multipass:
  desc: null
  value: true
weighted:
  desc: null
  value: false
average:
  desc: null
  value: false
random_weighted:
  desc: null
  value: false
render_freq:
  desc: null
  value: 100
save_freq:
  desc: null
  value: 0
save_dir:
  desc: null
  value: results/platform
save_frames:
  desc: null
  value: false
visualise:
  desc: null
  value: true
action_input_layer:
  desc: null
  value: 0
title:
  desc: null
  value: PDDQN
use_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685108967.794999
    t:
      1:
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 4
      - 5
    framework: torch
